### ISSUE TITLE
Need to set DOCKER_CONTENT_TRUST_* environment variables.

### ISSUE THREAD

**Issue by chrispat** [microsoft/vsts-docker#40]
working with a customer now that wants to see end-to-end CI/CD on VSTS … and ideally, I would like to use this plugin in some of the build steps … however, in order to use Docker Content Trust, one needs to set the following environment variables … `DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE` and `DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE` … and ideally, these should be set with VSTS Secret Variables (https://www.visualstudio.com/en-us/docs/build/define/variables#secret-variables) … however, since VSTS Secret Variables cannot be decrypted into environment variables, the VSTS Docker plugin can’t be used with Docker Content Trust

**Comment by dhanvi** [comment]
@chrisrpatterson VSTS secret variables can be decrypted (work around) by running a shell script which sets the environment variables and adding the VSTS variables as the arguments. 

![shell-github-vsts](https://cloud.githubusercontent.com/assets/6671379/26582872/52ca5338-4560-11e7-95c4-c4248a725ec5.PNG)

PS: the VSTS private variables will be redacted in the build logs
