### ISSUE TITLE
Service Discovery and Application Groups

### ISSUE THREAD

**Issue by luismendozamx** [Microsoft/vsts-docker#45]
Hi,

We have been using this integration with a DC/OS cluster for a while. As our application grows we have a few questions regarding how we should do service discovery. 

Right now we deploy a set of services using a single docker-compose. Our service discovery is handled by using links between services which enables us to call a service using its name. This works well when having all our services deployed with one docker-compose. The problem comes when deploying multiple services separately.

The integration requires us to define an `Application Group Name`, `Application Group Qualifier` and `Application Group Version`. The `Application Group Version` uses `$(Release.ReleaseId).$(Release.AttemptNumber)` variables to create unique groups for blue-green deploys. The problem with this is every time we deploy a service it's `Marathon DNS Name` and `Marathon App ID` change. Making it imposible to have a single service name to use for referencing internally exposed services.

The main questions we have are:

* What's the best strategy to do service discovery among separately deployed applications?
* Is there a way to define a static Application ID without losing the ability to do blue-green deploys?

For reference we are using [marathon-lb](https://github.com/mesosphere/marathon-lb) to handle route access for our services. 

We have also been exploring [linkerd](https://linkerd.io/) as an alternative for service discovery and load balancing between applications. The existing integration with DC/OS seems to suite our needs, but not having a static application ID causes the same issues when referencing services whose name changes with every deploy.

Thank you very much!

P.S. If there is a way we can contribute to this integration we'd love to help. We are investing heavily on Azure, ACS and VSTS for all our workflow.

**Comment by stepro** [comment]
The docker deploy task isn't well documented, but I believe there is a solution for you here. If, in your docker-compose file for a service, you specify a "ports" array, then you are making a statement that you want to publish a port from the container. In regular docker-compose terms, this means to publish the port on the host, but in DC/OS that doesn't make sense. The deploy task interprets this statement as meaning you want to publish the port so it is available to other services running in the DC/OS cluster.

What you'll find is that once you specify an entry in "ports", say "80", that an internal virtual IP address is created that remains consistent regardless of the version of the service that has been deployed. It can be referenced like this:

```
123456789.myservice.internal.marathon.l4lb.thisdcos.directory
```

The '123456789' is a hash of the application group qualifier and name while "myservice" is the name of the service that was deployed. This URL does not change across versions of the service. During a rolling update of the service, this URL load balances over both the old and the new versions.

Let me know if this doesn't make sense or if you have other questions.

**Comment by luismendozamx** [comment]
Thank you for the quick response @stepro! That's exactly the answer we were looking for. I just hadn't realized that VIP wasn't changing across deploys of the same service. 

We'd love to see some documentation on the integration whenever it is available.
