### ISSUE TITLE
Option to pull a newer version of images on build.

### ISSUE THREAD

**Issue by jdharmon** [Microsoft/vsts-docker#47]
By default ```docker build``` and ```docker-compose build``` will not pull the latest versions of base images if the image already exists on the host. Both have a ```--pull``` option to check for an updated image. The Docker and Docker Compose tasks should allow this option to be specified.

**Comment by stepro** [comment]
+1

However, please open this issue on the Microsoft/vsts-tasks repo - the Docker and Docker Compose tasks have been officially moved out of an extension and into the VSTS "box".

**Comment by jdharmon** [comment]
Thanks. Opened https://github.com/Microsoft/vsts-tasks/issues/4423
